services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: event-register
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - '3336:3306'
    networks: 
      - devjf-network
networks:
  devjf-network:
    driver: bridge